name: 'Version Check'
description: 'Check version changes in any file format (JSON, YAML, TOML, XML)'
author: 'rxliuli'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  file:
    description: 'Path to the file to check (e.g., ./package.json, ./Cargo.toml)'
    required: true
  query:
    description: 'Dot-notation path to the version field (e.g., "version" or "package.version")'
    required: false
    default: 'version'

outputs:
  changed:
    description: 'Whether the version changed (true/false)'
  version:
    description: 'Current version number'
  previous_version:
    description: 'Previous version number'
  type:
    description: 'Type of version change (major/minor/patch/prerelease)'

runs:
  using: 'node24'
  main: 'dist/index.js'